spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

account:
  message: "Welcome to Klandodo Transportation related qa APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "support@klandodo.com"
  onCallSupport:
    - (647) 834-1811