spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

car:
  message: "Welcome to Klandodo Transportation related prod APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "support@klandodo.com"
  onCallSupport:
    - (647) 834-1811